### ISSUE TITLE
Test does not check for row element repetition/quantity

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/ttt-3-display_board-example#11]
The test checks for the two main elements:

``` ruby
("   |   |   ")
```

and

``` ruby
("-----------")
```

However, it does not check that there are the appropriate quantity. So, someone could get away with this answer:

``` ruby
def display_board
  puts "   |   |   "
  puts "-----------"
end
```

**Comment by PeterBell** [comment]
Hi @sammarcus looks to me like this has been fixed with the test at https://github.com/PeterBell/ttt-3-display_board-example-Instructors/blob/master/spec/display_board_spec.rb#L33 so I'm gonna close this. Just reopen if any questions. Thanks so much!
