### ISSUE TITLE
Lab not openning properly

### ISSUE THREAD

**Issue by cleckie** [learn-co-curriculum/ttt-3-display_board-example#14]
ttt-3-display_board-example-kwk-000 folder is not appearing on the left column directory even though it is open. Also the README.md is blank and because I can't open the files, I can't see any code for this lab. What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/19671697/15698746/20423856-27fa-11e6-8531-7016c24dbd74.png)
![image](https://cloud.githubusercontent.com/assets/19671697/15698750/29f203f4-27fa-11e6-9651-90182b1b9ce7.png)

**Comment by AnnJohn** [comment]
hi @cleckie sorry for the delay. we use this space for issues specifically related to the content of the lessons. Since this looks like a technical bug could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. Thanks!
