### ISSUE TITLE
Cannot progress to next lesson

### ISSUE THREAD

**Issue by kkterai** [learn-co-curriculum/ttt-3-display_board-example#16]
Dear Learn,

Please help. I cannot progress to the next lab because "Submit Pull Request" does not seem to register when I type "learn submit" in the terminal and press enter. It submits the lesson in the terminal, but not at Learn.co. On the right rail, this is what it currently says and the color it appears in:

QUESTIONS CURRENTLY OPEN
Forked this Lab - Green
Passed Local Tests - Green 
**_Submit Pull Request - Grey (unable to click)
NEXT LESSON - Grey_** (unable to click)

Please advise.

Thanks in advance!
#15

Kenlyn

**Comment by AnnJohn** [comment]
hi again, sorry for the delay! we use this space for issues specifically related to the content in the lessons so could you please file a bug report for this? thanks!
