### ISSUE TITLE
Local Build Failing

### ISSUE THREAD

**Issue by shannonmatloob** [learn-co-curriculum/ttt-3-display_board-example#17]
![screen shot 2016-06-27 at 5 41 25 pm](https://cloud.githubusercontent.com/assets/13443905/16400236/6d0e79d0-3c8e-11e6-956f-fa2b72e02daf.png)

For some reason, my Learn IDE is no longer allowing me to run the test suite with "Learn" anymore.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
