### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/ttt-3-display_board-example#18]
Hey,  I was just thinking it would be cool if there was a simple journal feature on Learn. Like a button that drops down a little pane, where you can write about what you learned from the lesson or think through things you're having trouble with. Like a scratchpad basically. except with capability to save the content if necessary, and search by highlighted text like on a kindle

**Comment by AnnJohn** [comment]
hi @ode-to-the-code thanks for the great suggestion. it's something that we've had on the roadmap for the past year so definitely on our minds too. we're not yet ready to move forward with it because of other priorities but will do so at some point in the future. thanks!
