### ISSUE TITLE
The Display Tic Tac Board Example Lab

### ISSUE THREAD

**Issue by theOtherRan** [learn-co-curriculum/ttt-3-display_board-example#2]
As I was working on this lab, I broke it down piece by piece, till eventually the following method that I used was able to pass the test. 

def display_board
  cell = "   |   |   "
  divider = '-----------'
  puts cell
  puts divider
end

Which results in just the top portion of the board being printed out:
##    |   |   

I considered it incomplete, since I was still working on adding to the code block for the method, but the lab and its test suite signaled that all conditions were satisfied. Regards.

**Comment by aviflombaum** [comment]
Hi @theOtherRan - ya, it's hard to write tests that cover every case but still provide flexibility in solutions. We'll look into this.

**Comment by mikeagreen3** [comment]
I also ran into this issue. I here's the test I came up with to test it... Though I'm sure it also causs some issues 

``` ruby
it 'prints a 3x3 tic tac toe board' do
  output = capture_puts{ display_board }
  output_array = output.split "\n"

   expect(output_array[0]).to include("   |   |   ")
   expect(output_array[1]).to include("-----------")
   expect(output_array[2]).to include("   |   |   ")
   expect(output_array[3]).to include("-----------")
   expect(output_array[4]).to include("   |   |   ")
end
```

Here's what I would've written in the commit message:

> The original test check to see if the string that returned from capture_puts
> included the elements of the tic tac toe board. The test could be fooled with an
> output that just contained the cell row and the separator row. To fix this issue
> the commit breaks the output string into an array based on newline and checks
> each of the rows in the array contains the correct string. The basic structure
> of the test remains the same but it will require the student to build the
> complete game board.

**Comment by PeterBell** [comment]
Hi @theOtherRan thanks so much for the input - very much appreciated. Thanks @aviflombaum for the comment and @magreen03 for a great solution. Looks like this has been resolved (see https://github.com/PeterBell/ttt-3-display_board-example-Instructors/blob/master/spec/display_board_spec.rb#L33 ). I'm going to close this, but if you have any additional questions or comments feel free to reopen. Thanks again for the input - very much appreciated!
