### ISSUE TITLE
Rspec tests are failing even though the Tic Tac Toe board is displaying correctly.

### ISSUE THREAD

**Issue by nomi474** [learn-co-curriculum/ttt-3-display_board-example#21]
My code displays the Tic Tac Toe board just fine, but two of the rspec tests are failing!! Any suggestions how to bypass that?
Here's my code.

# Define a method display_board that prints a 3x3 Tic Tac Toe Board
def display_board
  row = "-----------"
  column = "   |"
  i = 1
  while i < 6 do
    if i % 2 == 0
      puts row
    else
      print column
      puts column
    end
    i = i + 1
  end
end

**Comment by cjbrock** [comment]
Hi @nomi474! If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
