### ISSUE TITLE
can't open dispaly_board.rb file

### ISSUE THREAD

**Issue by vatsalyanandwana** [learn-co-curriculum/ttt-3-display_board-example#22]
I have tried many times but i cannot find display_board.rb in file in side pane or in the lib folder to complete the lab

**Comment by cjbrock** [comment]
Hi @vatsalyanandwana! If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
