### ISSUE TITLE
GitHub markdown disregards whitespace in code styling

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/ttt-3-display_board-example#6]
This might be the most frequently raised question in this track. It turns out GH was throwing out the extra spaces we had in there. I guess it does it by design, and when you encapsulate it in a snippet you can't have consecutive whitespace. 

I tried to fix it in https://github.com/learn-co-curriculum/ttt-3-display_board-example/pull/5, it's an improvement but still not so great. 

Perhaps the test could also allow forgiveness for single spaces in each square instead of a strict three.

**Comment by AnnJohn** [comment]
I used `<pre>` tags to make the formatting clearer.

**Comment by sammarcus** [comment]
I would still propose the test allow for additional forgiveness. I believe this lab and the one following it are hands down the most frequently debugged labs in the qualifying track, and all solely for whitespace issues. Just tonight I debugged three students in an hour regarding this problem. Consistently a handful will come in every single night for the very same issue.

The problem is exacerbated for a variety of reasons I've outlined in my earlier issues, mainly that rspec does not provide a visually meaningful error report for styling things like this. This is a bigger problem than it may seem, because students are essentially stuck since they know it's not working but can't discern why.

Example:

![image](https://cloud.githubusercontent.com/assets/8689264/10861894/cb94e22a-7f68-11e5-85c3-7e7dacc6e1aa.png)

They see there is an error, but it is not visually possible to understand why it doesn't satisfy the expectation.

I understand the devil is in the details, but I'm not sure it's the spirit of this lab to have someone frustrated for an hour (frequently the time frame they tell me) over a single spacing character, especially when they prove they understand the other concepts it is intended to teach.

**Comment by PeterBell** [comment]
Hey @sammarcus I'm seeing less problems/issues around this lab than a bunch of the others now - I haven't seen any issues around this particular problem in the last couple of weeks. Given this is a bit of an old issue (chronologically) if you don't mind I'm gonna close it. If this is still an issue I'm sure we'll end up opening a new issue and finding a resolution. Thanks!
