### ISSUE TITLE
Description of Board Rules

### ISSUE THREAD

**Issue by just-Bri** [learn-co-curriculum/ttt-3-display_board-example#7]
This makes it seem like I should be creating an array, which has a separate variables for each "   " and "|"
Once I looked into the spec file I realized it was supposed to be a single string for each row.
# 

Board Rules

Each cell is presented by a string with 3 spaces:
"   "
Each row has 3 cells, the middle separated by 2 | (pipe) characters:
   |   |   
# There are 3 rows, with 2 separating lines of 11 - (dash) characters: -----------

**Comment by PeterBell** [comment]
Hi @reifnotreef thanks so much for the feedback! I was also tempted at first to be creating an array, but as I read down the instructions I realized that it said "You can build a single big string and output it once or you can output each line individually" so I think that makes it pretty clear what's being looked for. I'm going to close this, but if you have any additional questions or comments feel free to reopen. Thanks again for the input - very much appreciated!
