### ISSUE TITLE
I'm sorry, but I must be reading something wrong in the spec. 

### ISSUE THREAD

**Issue by Jurtly** [learn-co-curriculum/ttt-3-display_board-example#8]
Please forgive me for bothering, but I'm stuck thinking that I already got it! lol please, if i may beg someone to review and just tell me that i have it right or wrong. Not the answer!!!

<h1> Thank you so much your time </h1>

**Comment by AnnJohn** [comment]
Hi @Jurtly please use the Ask a Question tool within Learn and someone will get back to you right away and help you out! Thanks
