### ISSUE TITLE
when I used print instead of puts in the method, it still tested correct

### ISSUE THREAD

**Issue by wu-wu-wu** [learn-co-curriculum/ttt-3-display_board-example#9]
using PRINT executes the board with no newlines which is wrong:

```
|   |   -----------   |   |   -----------   |   |   => nil
```

should be PUTS, the local tests should check for that.

**Comment by PeterBell** [comment]
Hey @wu-wu-wu thanks so much for the feedback. In practice the tests _do_ test for the newlines, so they test for either using puts or using print with \n so they seem to be testing the right thing. Going to close this, but if you have any additional questions or comments feel free to reopen. Thanks again for the input!
